#!/usr/bin/bash
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus

$notes="$HOME/Documents/Notas"
devices=(
	#Dispositivos definidos em ssh
	"dariolaptop"
)

for device in ${devices[@]}; do
	# Verificar conexão
	ssh -q -o BatchMode=yes  -o StrictHostKeyChecking=no -o ConnectTimeout=5 "$device" 'exit 0'
	go="$?"
	if [ "$go" = "0" ]; then
	    #Sincronizar configuração
	    rsync -uvrP --delete "${notes}/*" $device:~/Documents/Notas
        notify-send "Notes sync 📓" "Devices ${devices[@]} updated with success!"
	fi
done
