#!/usr/bin/sh
# My brightness script
# USAGE: brightness +/- 10 (increases/reduces the brightness bt 10)
device=$(ls /sys/class/backlight)
state=$(cat /sys/class/backlight/$device/actual_brightness)
max=$(cat /sys/class/backlight/$device/max_brightness)
new_state=$(($state $1 $2))

if [ $new_state -lt $max ] && [ $new_state -gt 0 ]; then
    printf "$new_state\n" >> /sys/class/backlight/$device/brightness
fi

notify-send "☀  Brightness: $new_state" -r 100 -t 700
